name: Docker build and push

inputs:
  github_username:
    description: GitHub Container Registry username
    required: true
  github_token:
    description: GitHub Container Registry token
    required: true
  registry:
    description: Registry to push the image to
    required: true

outputs:
  docker_image_tag:
    description: Docker Container tag
    value: ${{ steps.image.outputs.tag }}

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3

    # Docker image tag
    - id: image
      run: |
        echo "tag=$CONTAINER_REGISTRY/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]'):$GITHUB_SHA" >> $GITHUB_OUTPUT
      env:
        CONTAINER_REGISTRY: ${{ inputs.registry }}
      shell: bash

    # Login to GitHub Container Registry
    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.github_username }}
        password: ${{ inputs.github_token }}

    # Docker build & push
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.image.outputs.tag }}
        build-args: |
          GIT_SHA=${{ github.sha }}
