inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

Rails/ApplicationController:
  Exclude:
    - app/controllers/support_interface/support_interface_controller.rb

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/staff/**/*
    - app/controllers/support_interface/staff_controller.rb

Rails/SaveBang:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Exclude:
    - spec/system/**/*

RSpec/InstanceVariable:
  Exclude:
    - spec/system/**/*

RSpec/AnyInstance:
  Exclude:
    - spec/logs/formatters/log_stash_formatter_spec.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/BlockDelimiters:
  Exclude:
    - app/services/feature_flag.rb

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - app/services/feature_flag.rb
