---
apiVersion: v1
kind: Service
metadata:
  name: refer-serious-misconduct-maintenance
spec:
  selector:
    app: refer-serious-misconduct-maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
