name: Prepare application environment
description: Performs setup steps common to jobs that need to run the application
inputs:
  skip-ruby:
    description: Allows skipping Ruby setup for jobs where it isn't required
    required: false
    default: "false"
  skip-node:
    description: Allows skipping Node.js setup for jobs where it isn't required
    required: false
    default: "false"
  node-version:
    description: The version of Node.js to install
    required: false
    default: "18.x"

runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.skip-ruby == 'false' }}
      with:
        bundler-cache: true

    - uses: actions/setup-node@v3
      if: ${{ inputs.skip-node == 'false' }}
      with:
        node-version: ${{ inputs.node-version }}

    - run: npm install yarn -g
      if: ${{ inputs.skip-node == 'false' }}
      shell: bash

    - id: yarn-cache
      if: ${{ inputs.skip-node == 'false' }}
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    # Set up yarn cache
    - uses: actions/cache@v3
      if: ${{ inputs.skip-node == 'false' }}
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    # Install node.js dependencies
    - run: yarn install
      if: ${{ inputs.skip-node == 'false' }}
      shell: bash
