---
shared:
  :active_storage_variant_records:
    - id
    - blob_id
    - variation_digest
  :active_storage_blobs:
    - id
    - key
    - filename
    - content_type
    - metadata
    - service_name
    - byte_size
    - checksum
    - created_at
  :active_storage_attachments:
    - id
    - name
    - record_type
    - record_id
    - blob_id
    - created_at
  :feature_flags_features:
    - id
    - name
    - active
    - created_at
    - updated_at
  :referrers:
    - id
    - referral_id
    - first_name
    - created_at
    - updated_at
    - phone
    - job_title
    - last_name
    - complete
  :referral_evidences:
    - id
    - filename
    - referral_id
    - created_at
    - updated_at
  :referrals:
    - id
    - created_at
    - updated_at
    - first_name
    - last_name
    - previous_name
    - name_has_changed
    - date_of_birth
    - has_qts
    - email_address
    - trn
    - trn_known
    - email_known
    - address_known
    - address_line_1
    - address_line_2
    - town_or_city
    - postcode
    - country
    - personal_details_complete
    - phone_known
    - phone_number
    - age_known
    - contact_details_complete
    - user_id
    - allegation_format
    - allegation_details
    - dbs_notified
    - allegation_details_complete
    - has_evidence
    - evidence_details_complete
    - role_start_date_known
    - role_start_date
    - previous_misconduct_reported
    - employment_status
    - role_end_date
    - reason_leaving_role
    - job_title
    - same_organisation
    - duties_format
    - duties_details
    - teacher_role_complete
    - previous_misconduct_details
    - submitted_at
    - working_somewhere_else
    - eligibility_check_id
    - work_location_known
    - work_organisation_name
    - work_address_line_1
    - work_address_line_2
    - work_town_or_city
    - work_postcode
    - organisation_address_known
    - organisation_name
    - organisation_address_line_1
    - organisation_address_line_2
    - organisation_town_or_city
    - organisation_postcode
    - role_end_date_known
    - allegation_consideration_details
    - previous_misconduct_format
    - previous_misconduct_complete
    - ni_number
    - ni_number_known
  :organisations:
    - id
    - referral_id
    - created_at
    - updated_at
    - name
    - street_1
    - street_2
    - city
    - postcode
    - complete
  :eligibility_checks:
    - id
    - reporting_as
    - created_at
    - updated_at
    - serious_misconduct
    - teaching_in_england
    - unsupervised_teaching
    - is_teacher
    - complained
  :users:
    - id
    - email
    - remember_created_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - created_at
    - updated_at
    - otp_guesses
    - otp_created_at
    - uuid
  :staff:
    - id
    - email
    - reset_password_sent_at
    - remember_created_at
    - sign_in_count
    - current_sign_in_at
    - last_sign_in_at
    - current_sign_in_ip
    - last_sign_in_ip
    - confirmed_at
    - confirmation_sent_at
    - unconfirmed_email
    - failed_attempts
    - locked_at
    - created_at
    - updated_at
    - invitation_created_at
    - invitation_sent_at
    - invitation_accepted_at
    - invitation_limit
    - invited_by_type
    - invited_by_id
    - invitations_count
    - view_support
    - manage_referrals
    - deleted_at
  :validation_errors:
    - id
    - form_object
    - details
    - created_at
    - updated_at
  :reminder_emails:
    - id
    - referral_id
    - created_at
    - updated_at
  :uploads:
    - id
    - section
    - filename
    - uploadable_type
    - uploadable_id
    - created_at
    - updated_at
    - malware_scan_result
