layout: support_layout
parent_controller: "SupportInterface::SupportInterfaceController"
feature_flags:
  service_open:
    author: Felix Clack
    description: Allow users to access the service
  employer_form:
    author: Steve Laing
    description: Allow users to access the employer-specific form
  staff_http_basic_auth:
    author: Malcolm Baig
    description: Allow signing in as a staff user using HTTP Basic authentication. This is useful before staff users have been created, but should otherwise be inactive.
