layout: support_layout
parent_controller: "SupportInterface::SupportInterfaceController"
feature_flags:
  service_open:
    author: Felix Clack
    description: Remove the basic authentication when accessing the main
      website. Keeps it in place for the support interface. This flag should
      always be inactive on non-production deployments, to prevent accidental
      access by members of the public. Once the service goes live, this flag
      should always be active on production.
  eligibility_screener:
    author: Felix Clack
    description: When enabled, the eligibility screener will be shown to
      candidates. When disabled, redirect the visitor to the existing eligibility
      information page on GOV.UK.
  referral_form:
    author: Steve Laing
    description: Allow users to access the employer and public facing referral form.
  staff_http_basic_auth:
    author: Malcolm Baig
    description: Allow signing in as a staff user using HTTP Basic
      authentication. This is useful before staff users have been created, but
      should otherwise be inactive.
  send_reminder_email:
    author: Sebastian Zaremba
    description: Send the reminder emails 7 days before deletion for unsubmitted
      referrals that weren't updated in 83 days.
  fetch_malware_scan_result:
    author: Sebastian Zaremba
    description: >
      Fetch malware scan results for uploaded files.
      This flag should only be active for environments where malware scanning is enabled.
