delete_draft_referrals:
  cron: "every day at midnight"
  class: "DeleteDraftReferralsJob"

draft_referral_reminder:
  cron: "every day at 9 am"
  class: "DraftReferralsReminderJob"

fetch_malware_scan_results:
  cron: "*/30 * * * *"
  class: FetchMalwareScanResultsJob

send_entity_table_checks_to_bigquery:
  cron: "30 3 * * *" # Every day at 03:30
  class: "DfE::Analytics::EntityTableCheckJob"
