delete_draft_referrals:
  cron: "every day at midnight"
  class: "DeleteDraftReferralsJob"

draft_referral_reminder:
  cron: "every day at 9 am"
  class: "DraftReferralsReminderJob"

fetch_malware_scan_results:
  cron: "*/30 * * * *"
  class: FetchMalwareScanResultsJob
