name: Deploy environment to AKS
description: Deploys an application environment to AKS

inputs:
  environment:
    description: The name of the environment
    required: true
  image-tag:
    description: The image tag to deploy
    required: true
  azure-credentials:
    description: JSON object containing a service principal that can read from Azure Key Vault
    required: true
  pull-request-number:
    description: The pull request number which triggered this deploy.
    required: false

outputs:
  environment_url:
    description: The base URL for the deployed environment
    value: ${{ steps.set_outputs.outputs.ENVIRONMENT_URL }}

runs:
  using: composite

  steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.4
        terraform_wrapper: false

    - uses: DFE-Digital/github-actions/set-kubelogin-environment@master
      with:
        azure-credentials: ${{ inputs.azure-credentials }}

    - uses: google-github-actions/auth@v2
      with:
        project_id: refer-serious-misconduct
        workload_identity_provider: projects/737868692824/locations/global/workloadIdentityPools/refer-serious-misconduct/providers/refer-serious-misconduct

    - name: Terraform Apply
      shell: bash
      run: |
        make ci ${{ inputs.environment }} aks-terraform-apply
      env:
        DOCKER_IMAGE_TAG: ${{ inputs.image-tag }}
        PR_NUMBER: ${{ inputs.pull-request-number }}

    - name: Extract Terraform outputs
      shell: bash
      id: set_outputs
      run: |
        environment_url=$(terraform -chdir=terraform/application output -raw url)
        echo "ENVIRONMENT_URL=$environment_url" >> $GITHUB_OUTPUT

    - name: Run smoke tests
      shell: bash
      run: |
        environment_url=$(terraform -chdir=terraform/application output -raw url)
        echo "Check health for $environment_url/health/all.json..."
        curl -sS --fail "$environment_url/health/all.json" > /dev/null && echo "Health check passed for $environment_url" || echo "Health check failed for $environment_url"
