source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in feature_flags.gemspec.
gemspec

gem "govuk-components"
gem "govuk_design_system_formbuilder"
gem "pg"
gem "propshaft"

group :development, :test do
  gem "factory_bot_rails"
end

group :test do
  gem "capybara"
  gem "cuprite"
  gem "puma", "~> 5.0"
  gem "rspec-rails"
  gem "shoulda-matchers"
end
