name: Test

on:
  push:
    branches:
      - "**"

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/refer_serious_misconduct_test
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Setup DB
        run: bin/rails db:prepare

      - name: Run DfE Analytics
        run: bin/bundle exec rails dfe:analytics:check

      - name: Run tests
        run: bin/rails spec

      - name: Test coverage report
        uses: aki77/simplecov-report-action@v1
        with:
          failedThreshold: 90
          token: ${{ secrets.GITHUB_TOKEN }}
